#!/usr/bin/env python3
"""Generate content/reference/ from static/captures/manifest.json.

The catalog table on the widgets index is generated by gen_widgets.py; this
produces the fuller reference page — one row per widget with its constructor,
capture widths, MinSize and capture sizes, grouped by package, plus the
package-level API links.

Same rule as the widget pages: read the generated manifest, write nothing that
is not in it. If the framework adds a widget, this page picks it up.

Usage: scripts/gen_reference.py [--check]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MODULE = "github.com/serkanalgur/termmosaic"

GROUP_TITLES = {
    "widgets/block": "Core",
    "widgets/basic": "Core",
    "widgets/split": "Core",
    "widgets/form": "Forms",
    "widgets/data": "Data",
    "widgets/viz": "Visualization",
}

# Every package the framework ships, whether or not it holds widgets. Read from
# the framework's tree rather than invented, so a new package shows up.
PACKAGES = [
    ("", "The root package: the `Widget`, `Focusable` and `Minimizable` interfaces, plus the event types."),
    ("buffer", "The 16-byte `Cell`, `Buffer`, `SubBuffer`, `Span`, `Style`, `Colour`, borders and the span writers."),
    ("geometry", "Rectangles, `Align`, `ClampCount`, `Budget`, `Region` and `Priority` — the shared responsive arithmetic."),
    ("layout", "The constraint solver: `Length`, `Min`, `Max`, `Percentage`, `Ratio`, `Fill`, `Solve`, `Rect`."),
    ("input", "`Decode`, `Parser`, `Source`, `Config` — the input layer."),
    ("render", "`Renderer`, `Config`, `Pacer`, the cursor, and the encode-time colour and NO_COLOR decisions."),
    ("term", "`Terminal` and `Sink` — the two narrow interfaces, with the `x/sys` implementation and the headless sink."),
    ("headless", "The in-memory `Sink` and its cell-grid screen model, for tests without a terminal."),
    ("virtual", "The row-virtualization engine shared by `List`, `Table` and `Tree`."),
    ("widgets/block", "`Block` — the catalog's only owner of borders and titles."),
    ("widgets/basic", "`Text` and `Paragraph`."),
    ("widgets/split", "`Split` — the pane composer."),
    ("widgets/form", "`TextInput`, `TextArea`, `Select`, `Checkbox`, `Radio`, `Toggle`, `Tabs`, `Button`, `KeyHint`."),
    ("widgets/data", "`List`, `Table`, `Tree`, `Pager`."),
    ("widgets/viz", "`ProgressBar`, `Gauge`, `Meter`, `Sparkline`, `BarChart`."),
]


def render(manifest: dict) -> str:
    widgets = manifest["widgets"]
    groups: dict[str, list[dict]] = {}
    for w in widgets:
        groups.setdefault(w["package"], []).append(w)

    out: list[str] = [
        "---",
        'title: "Catalog and API"',
        # No slug: this file is content/reference/api.md, so its URL is already
        # /reference/api/. Hugo resolves a slug RELATIVE to the section, so the
        # "/reference/api" that used to be emitted here produced
        # /reference/reference/api/ and every nav entry 404'd - and a local
        # Hugo build cannot catch that, because it builds the wrong page happily.
        # The live-URL check is what found it.
        "weight: 61",
        'description: "Generated from the framework\'s capture manifest: every widget, its constructor, its MinSize and its capture sizes."',
        "toc: true",
        "---",
        "",
        "# Catalog and API",
        "",
        "**This page is generated** by `scripts/gen_reference.py` from",
        "`static/captures/manifest.json`, which is itself produced by",
        f"`cmd/capture` in the framework repository. It therefore cannot claim",
        f"anything the framework does not do: every row below is a fact about a",
        "widget that was constructed and rendered.",
        "",
        f"**{manifest['widgetCount']} widgets.** Counted, not estimated — see",
        "[the catalog index](/widgets/) for what is and is not included.",
        "",
        "> **pkg.go.dev is the authority on signatures.**",
        f"> <https://pkg.go.dev/{MODULE}> is generated from the source and can",
        "> never be out of date. This page is generated from a build artefact,",
        "> which is a weaker guarantee, and it exists because it carries the",
        "> things godoc does not: `MinSize()`, the capture widths, and which",
        "> package each widget belongs to.",
        "",
        "## Widgets by package",
        "",
    ]

    for pkg in sorted(groups, key=lambda p: list(groups).index(p)):
        entries = groups[pkg]
        title = GROUP_TITLES.get(pkg, pkg)
        out.append(f"### {title} — `{pkg}`")
        out.append("")
        out.append(
            f"[pkg.go.dev/{pkg}](https://pkg.go.dev/{MODULE}/{pkg})"
        )
        out.append("")
        out.append("| Widget | Constructor | `MinSize()` | Captures |")
        out.append("| --- | --- | --- | --- |")
        for w in entries:
            ms = w.get("minSize")
            cell = f"{ms['w']}×{ms['h']}" if ms else "—"
            widths = " × ".join(f"{c}×{h}" for c, h in zip(w["widths"], w["heights"]))
            out.append(
                f"| [`{w['name']}`](/widgets/{w['slug']}/) "
                f"| `{w['constructor']}` | {cell} | {widths} |"
            )
        out.append("")

    out += [
        "**`MinSize()` includes the widget's own chrome**, and every value above",
        "was **called**, not parsed — `NewTable(rect, cols).MinSize()` returns the",
        "real answer even though the thresholds are private constants. The",
        "framework does nothing with it; what to do when the available space is",
        "below it is the application's decision.",
        "",
        "## Packages",
        "",
        "| Package | What it holds |",
        "| --- | --- |",
    ]
    for pkg, note in PACKAGES:
        path = f"{MODULE}/{pkg}" if pkg else MODULE
        label = f"`{pkg}`" if pkg else "*(root)*"
        out.append(f"| {label} | {note} [pkg.go.dev](https://pkg.go.dev/{path}) |")

    out += [
        "",
        "## The one interface that is held fixed",
        "",
        "```go",
        "type Widget interface {",
        "    Bounds() Rect",
        "    Draw(buf *buffer.Buffer)",
        "    Invalidate()",
        "    Handle(Event) bool",
        "}",
        "```",
        "",
        "**Four methods, unchanged across all eight architecture decisions.** That",
        "is the most stable thing about a pre-alpha project: a widget written",
        "against it today is the part most likely to still compile after the API",
        "settles. The two optional interfaces are `Focusable` and `Minimizable` —",
        "both discoverable by a type assertion, both costing nothing to omit.",
        "",
        "See [Widgets and focus](/concepts/widgets-and-focus/) for what `Draw` may",
        "and may not do, and [ADR 0003](/adr/0003-renderer-mode/) for why the",
        "interface is this small.",
        "",
        "## Related",
        "",
        "- [The catalog](/widgets/) — the same 22, one page each, with captures.",
        "- [Architecture decisions](/adr/) — the reasoning behind every row above.",
        "- [Limitations](/limitations/) — what the framework does not do.",
    ]
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    manifest = json.loads(
        (REPO / "static/captures/manifest.json").read_text(encoding="utf-8")
    )
    page = render(manifest)
    target = REPO / "content/reference/api.md"
    target.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != page:
            print("content/reference/api.md is stale; run scripts/gen_reference.py")
            return 1
        print("content/reference/api.md is up to date")
        return 0

    target.write_text(page, encoding="utf-8")
    print(f"wrote {target.relative_to(REPO)} ({manifest['widgetCount']} widgets)")
    return 0


if __name__ == "__main__":
    sys.exit(main())