#!/usr/bin/env python3
"""Generate the 22 widget pages from data the framework already produced.

Three inputs, three different provenances, and the script refuses to invent any
of them:

  static/captures/manifest.json  generated by cmd/capture in the framework repo.
                                 Names, packages, constructors, summaries, notes,
                                 MinSize, the three capture widths. Never edited.
  data/godoc.json                extracted from the framework's Go source by
                                 --refresh-godoc. Cached so the site repo can be
                                 rebuilt without a framework checkout.
  data/widget_prose.json         hand-written. "When NOT to use this" is the one
                                 section a capture cannot generate.

Output: content/widgets/<slug>.md, committed. Re-running is idempotent; a
non-empty diff means an input moved.

Usage:
  scripts/gen_widgets.py                          # rebuild from cached inputs
  scripts/gen_widgets.py --refresh-godoc          # re-extract from the framework
  scripts/gen_widgets.py --framework ../Projects/termmosaic --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Widget -> the framework file whose `type <Widget> struct` doc comment carries
# the package narrative, the key contract and the accessibility notes. Sourced by
# reading widgets/<pkg>/*.go, not assumed: --refresh-godoc fails if a name below
# has no such declaration.
WIDGET_SOURCE = {
    "block": ("widgets/block/block.go", "Block"),
    "text": ("widgets/basic/basic.go", "Text"),
    "paragraph": ("widgets/basic/basic.go", "Paragraph"),
    "split": ("widgets/split/split.go", "Split"),
    "textinput": ("widgets/form/textinput.go", "TextInput"),
    "textarea": ("widgets/form/textarea.go", "TextArea"),
    "select": ("widgets/form/select.go", "Select"),
    "checkbox": ("widgets/form/checkbox.go", "Checkbox"),
    "radio": ("widgets/form/radio.go", "Radio"),
    "toggle": ("widgets/form/toggle.go", "Toggle"),
    "tabs": ("widgets/form/tabs.go", "Tabs"),
    "button": ("widgets/form/button.go", "Button"),
    "keyhint": ("widgets/form/keyhint.go", "KeyHint"),
    "list": ("widgets/data/list.go", "List"),
    "table": ("widgets/data/table.go", "Table"),
    "tree": ("widgets/data/tree.go", "Tree"),
    "pager": ("widgets/data/pager.go", "Pager"),
    "progressbar": ("widgets/viz/progressbar.go", "ProgressBar"),
    "gauge": ("widgets/viz/gauge.go", "Gauge"),
    "meter": ("widgets/viz/meter.go", "Meter"),
    "sparkline": ("widgets/viz/sparkline.go", "Sparkline"),
    "barchart": ("widgets/viz/barchart.go", "BarChart"),
    "menu": ("widgets/menu/menu.go", "Menu"),
    "dialog": ("widgets/dialog/dialog.go", "Dialog"),
}

# Package doc -> the file whose leading comment is the package narrative, and the
# one extra heading worth repeating on every page from that package. Chosen
# explicitly rather than "all of them": the package docs run long, and a widget
# page that pastes 2 KB of package contract obscures the widget.
PKG_SOURCE = {
    "widgets/block": ("block", None),
    "widgets/basic": ("basic", None),
    "widgets/split": ("split", "The one interface Split adds"),
    "widgets/form": ("form", "What the whole package shares"),
    "widgets/data": ("data", "The rules every widget here obeys"),
    "widgets/viz": ("viz", "The three rules every widget here obeys"),
    "widgets/menu": ("menu", None),
    "widgets/dialog": ("dialog", None),
}

# Go doc headings that become their own widget-page section. Everything else in a
# type's doc comment becomes the intro prose. The order here is the order on the
# page; a heading not in this map is dropped, because an unmapped Go heading
# would silently become prose and read as a heading that is not there.
SECTION_ORDER = ["Key contract", "Accessibility", "Cost", "Colour is never the only signal"]


# --------------------------------------------------------------------------- #
# godoc extraction
# --------------------------------------------------------------------------- #

def strip_doc(lines: list[str]) -> list[str]:
    """Drop the `//` prefix and the single space Go convention adds after it."""
    out = []
    for line in lines:
        if line.startswith("// "):
            out.append(line[3:])
        elif line == "//":
            out.append("")
        elif line.startswith("//"):
            out.append(line[2:])
        else:
            out.append(line)
    return out


def type_doc(src: str, typename: str) -> list[str]:
    """Return the doc comment immediately preceding `type <typename> ...`."""
    lines = src.split("\n")
    idx = None
    for i, line in enumerate(lines):
        if re.match(rf"^type {re.escape(typename)}\b", line):
            idx = i
            break
    if idx is None:
        raise LookupError(f"no declaration for `type {typename}`")

    # The declaration may carry the name on its own line or share a line with
    # other members; walk back over the comment block either way.
    doc: list[str] = []
    i = idx - 1
    while i >= 0 and lines[i].startswith("//"):
        doc.append(lines[i])
        i -= 1
    return list(reversed(strip_doc(doc)))


def split_sections(lines: list[str]) -> tuple[str, dict[str, str]]:
    """Split a Go doc comment into (intro prose, {# Heading: body} sections)."""
    intro: list[str] = []
    sections: dict[str, list[str]] = {}
    current: str | None = None

    for line in lines:
        heading = re.match(r"^# (.+?)\s*$", line)
        if heading:
            current = heading.group(1)
            sections[current] = []
            continue
        if current is None:
            intro.append(line)
        else:
            sections[current].append(line)

    return "\n".join(intro).strip(), {k: "\n".join(v).strip() for k, v in sections.items()}


def package_doc(src: str, pkgname: str) -> list[str]:
    """Return the doc comment immediately preceding the `package` clause."""
    lines = src.split("\n")
    doc: list[str] = []
    seen = False
    for line in lines:
        if line.startswith(f"package {pkgname}"):
            break
        if line.startswith("//"):
            doc.append(line)
            seen = True
        elif line.strip() == "":
            if seen:
                break
        elif seen:
            break
    return strip_doc(doc)


def contract_table(body: str) -> tuple[str, list[tuple[str, str]], str]:
    """Split a `# Key contract` body into (prose before, rows, prose after).

    The binding rows are an indented block a human wrote as aligned columns:

        activate      KeyEnter, KeySpace
        focus         a left click inside Bounds, which also activates

    They are recognised by their leading tab, not by their alignment, so the
    prose around them — which carries the negative claims that make a contract
    worth reading ("KeyTab is NOT consumed") — is kept rather than swallowed.
    """
    prose: list[str] = []
    rows: list[tuple[str, str]] = []
    tail: list[str] = []
    in_rows = False

    for raw in body.split("\n"):
        if raw.startswith("\t"):
            parts = re.split(r"\s{2,}", raw.strip())
            if len(parts) >= 2:
                rows.append([parts[0].strip(), " ".join(parts[1:]).strip()])
                in_rows = True
                continue
            # A single column: the effect wrapped onto its own aligned line.
            if rows:
                rows[-1][1] = (rows[-1][1] + " " + raw.strip()).strip()
            else:
                rows.append([raw.strip(), ""])
            in_rows = True
            continue
        if raw.strip() == "":
            continue
        # Prose before the first row introduces it; prose after it qualifies it.
        (tail if in_rows else prose).append(raw.strip())

    return " ".join(prose), rows, " ".join(tail)


LIST_MARKER = re.compile(r"^\s*(?:[-*]|\d+\.)\s+(.*)$")


def render_intro(text: str) -> str:
    """Go doc prose -> markdown, block by block.

    Go doc comments use three shapes that markdown renders differently: prose
    paragraphs, literal blocks indented with a tab, and lists — bulleted or
    numbered — whose continuation lines are indented to align under the first
    item. Rewrapping prose and preserving indentation renders all three, so this
    walks lines and classifies each into one of the three rather than splitting
    on blank lines, which would fuse a three-item list into one paragraph.
    """
    blocks: list[tuple[str, list]] = []
    current: list | None = None

    def begin(kind: str):
        nonlocal current
        current = [kind, []]
        blocks.append(current)

    for raw in text.split("\n"):
        if raw.startswith("\t"):
            # Literal block. Continuation lines inside one are indented too.
            if current is None or current[0] != "pre":
                begin("pre")
            current[1].append(raw[1:])
            continue
        if not raw.strip():
            current = None
            continue
        marker = LIST_MARKER.match(raw)
        if marker:
            if current is None or current[0] != "list":
                begin("list")
            current[1].append([marker.group(1)])
            continue
        if current is not None and current[0] == "list":
            current[1][-1].append(raw.strip())
            continue
        if current is None or current[0] != "p":
            begin("p")
        current[1].append(raw.strip())

    out: list[str] = []
    for kind, body in blocks:
        if kind == "p":
            out.append(" ".join(body))
        elif kind == "list":
            out.append("\n".join("- " + " ".join(item) for item in body))
        else:
            out.append("\n".join(("    " + ln) if ln.strip() else "" for ln in body))
    return "\n\n".join(x for x in out if x.strip())


def refresh_godoc(framework: Path) -> dict:
    if not framework.is_dir():
        sys.exit(f"framework repo not found at {framework}")

    # Package narrative is identical for every widget in a package; extract once.
    packages: dict[str, dict] = {}
    for pkg, (base, extra) in PKG_SOURCE.items():
        src = (framework / pkg / f"{base}.go").read_text(encoding="utf-8")
        intro, sections = split_sections(package_doc(src, base))
        packages[pkg] = {"intro": intro, "extra": sections.get(extra) if extra else None}

    out: dict[str, dict] = {}
    for slug, (rel, typename) in WIDGET_SOURCE.items():
        src = (framework / rel).read_text(encoding="utf-8")
        intro, sections = split_sections(type_doc(src, typename))
        entry: dict = {"intro": intro, "sections": sections}
        if "Key contract" in sections:
            before, rows, after = contract_table(sections["Key contract"])
            entry["keyContract"] = {"before": before, "rows": rows, "after": after}
        out[slug] = entry
    return {"packages": packages, "widgets": out}


# --------------------------------------------------------------------------- #
# markdown rendering
# --------------------------------------------------------------------------- #

def render_key_contract(prose: str, rows: list[list[str]], tail: str) -> str:
    parts = []
    if prose:
        parts.append(prose)
    if rows:
        table = ["| Keys | Effect |", "| --- | --- |"]
        for action, keys in rows:
            table.append(f"| `{action}` | {keys or '—'} |")
        parts.append("\n".join(table))
    if tail:
        parts.append(tail)
    return "\n\n".join(parts)


def bullet(text: str) -> str:
    """Prefix a `- ` unless the hand-written line already carries a marker."""
    return text if text.lstrip().startswith(("- ", "* ")) else "- " + text


def render_page(w: dict, prose: dict, godoc: dict, pkgs: dict) -> str:
    slug = w["slug"]
    g = godoc.get(slug, {})
    lines: list[str] = []

    # ---- front matter ----------------------------------------------------- #
    fm = {
        "title": w["name"],
        "weight": w["weight"],
        "description": w["summary"],
        "widgetName": w["name"],
        "widgetPackage": w["package"],
        "widgetConstructor": w["constructor"],
        "capture": slug,
    }
    lines.append("---")
    for key, value in fm.items():
        lines.append(f'{key}: {json.dumps(value)}')
    lines.append("---")
    lines.append("")

    # ---- 1. what it is --------------------------------------------------- #
    lines.append(w["summary"])
    lines.append("")
    lines.append(
        f"Package `{w['package']}`. API reference: "
        f"[pkg.go.dev/{w['package']}](https://pkg.go.dev/github.com/serkanalgur/termmosaic/{w['package']})."
    )
    lines.append("")
    if g.get("intro"):
        lines.append(render_intro(g["intro"]))
        lines.append("")

    # ---- 2. captures ----------------------------------------------------- #
    lines.append("## Rendered output")
    lines.append("")
    lines.append("{{< widget-capture " + slug + " >}}")
    lines.append("")
    # The capture tool's own note, unless a hand-written one overrides it. The
    # override exists because the manifest and the godoc disagreed once: the
    # KeyHint note said the bar drops its lowest-priority bindings, the godoc and
    # the 40-column capture both say it truncates with a marker. Where they
    # disagree the capture is the evidence and the godoc is right.
    note = prose.get("note") or w.get("note")
    if note:
        lines.append(f"> **About this capture.** {note}")
        lines.append("")

    # ---- 3. package context ---------------------------------------------- #
    pkg = pkgs.get(w["package"], {})
    if pkg.get("intro"):
        lines.append("## Package context")
        lines.append("")
        lines.append(render_intro(pkg["intro"]))
        lines.append("")
    if pkg.get("extra"):
        lines.append(render_intro(pkg["extra"]))
        lines.append("")

    # ---- 4. constructing it ---------------------------------------------- #
    lines.append("## Constructing it")
    lines.append("")
    lines.append(f"```go\n{w['constructor']}\n```")
    lines.append("")
    if prose.get("constructing"):
        lines.append(prose["constructing"])
        lines.append("")
    for field in prose.get("fields", []):
        lines.append(f"- `{field['name']}` — {field['doc']}")
    if prose.get("fields"):
        lines.append("")

    # ---- 5. key contract ------------------------------------------------- #
    kc = g.get("keyContract")
    if kc and kc["rows"]:
        lines.append("## Key contract")
        lines.append("")
        lines.append(render_key_contract(kc["before"], kc["rows"], kc["after"]))
        lines.append("")
        if prose.get("keyNotes"):
            lines.append(prose["keyNotes"])
            lines.append("")

    # ---- 6. accessibility ------------------------------------------------ #
    a11y = g.get("sections", {}).get("Accessibility")
    if a11y:
        lines.append("## Accessibility")
        lines.append("")
        lines.append(render_intro(a11y))
        lines.append("")
    if prose.get("accessibility"):
        lines.append("## More on accessibility")
        lines.append("")
        lines.append(prose["accessibility"])
        lines.append("")

    # ---- 7. cost --------------------------------------------------------- #
    cost = g.get("sections", {}).get("Cost")
    if cost:
        lines.append("## What it costs")
        lines.append("")
        lines.append(render_intro(cost))
        lines.append("")

    # ---- 8. when not to use it (hand-written) ---------------------------- #
    lines.append("## When not to use it")
    lines.append("")
    for para in prose["whenNotToUse"]:
        lines.append(para)
        lines.append("")
    if prose.get("instead"):
        lines.append("**Instead:** " + prose["instead"])
        lines.append("")

    # ---- 9. related ------------------------------------------------------ #
    lines.append("## Related")
    lines.append("")
    related = [bullet(r) for r in prose.get("related", [])]
    related.append("- [TermMosaic limitations that apply to every widget](/limitations/)")
    related.append(
        f"- Source: [`{w['package']}` on GitHub]"
        f"(https://github.com/serkanalgur/termmosaic/tree/main/{w['package']})"
    )
    lines.append("\n".join(related))

    return "\n".join(lines).rstrip() + "\n"


def render_index(manifest: dict, prose: dict) -> str:
    groups: dict[str, list[dict]] = {}
    for w in manifest["widgets"]:
        groups.setdefault(w["package"], []).append(w)

    lines = [
        "---",
        'title: "Widgets"',
        "weight: 40",
        'description: "All 22 widgets, with a captured frame at three widths for each."',
        "---",
        "",
        f"TermMosaic ships **{manifest['widgetCount']} widgets**. That number is the whole claim and it is "
        "counted, not estimated: it is every exported type with a `New…` constructor that satisfies "
        "`termmosaic.Widget`, and `buffer.Buffer` is deliberately not on the list because it is what widgets "
        "draw *into*, not a widget.",
        "",
        "`widgets/form/optionlist.go` is an unexported shared helper behind `Select`, `Tabs` and `KeyHint`; it is "
        "not a twenty-third widget.",
        "",
        "> There is no `Form` container widget. A `Form` type would have been a second way to do what "
        "[ADR 0004](/adr/0004-layout-engine/)'s constraint solver and the `layout` package already do, so it was "
        "not built. See [Forms](/guides/forms/) for how the form widgets compose.",
        "",
        "Every page below carries the widget's captured frame at 40, 80 and 120 columns. Read "
        "[what a capture can and cannot show](/limitations/#captures-are-cell-grids-not-terminal-screenshots) "
        "before you read one as a promise about your own terminal.",
        "",
    ]
    titles = {
        "widgets/block": "Core",
        "widgets/basic": "Core",
        "widgets/split": "Core",
        "widgets/form": "Forms",
        "widgets/data": "Data",
        "widgets/viz": "Visualization",
    }
    for pkg, entries in groups.items():
        lines.append(f"## {titles.get(pkg, pkg)} — `{pkg}`")
        lines.append("")
        lines.append("| Widget | Summary | MinSize |")
        lines.append("| --- | --- | --- |")
        for e in entries:
            ms = e.get("minSize")
            cell = f"{ms['w']}×{ms['h']}" if ms else "—"
            lines.append(
                f"| [`{e['name']}`](/widgets/{e['slug']}/) | {e['summary']} | {cell} |"
            )
        lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--framework", default=None, help="path to the termmosaic checkout")
    ap.add_argument("--refresh-godoc", action="store_true")
    ap.add_argument("--check", action="store_true", help="fail if output would change")
    args = ap.parse_args()

    manifest = json.loads((REPO / "static/captures/manifest.json").read_text(encoding="utf-8"))
    prose_all = json.loads((REPO / "data/widget_prose.json").read_text(encoding="utf-8"))

    framework = Path(args.framework) if args.framework else None
    godoc_path = REPO / "data/godoc.json"

    if args.refresh_godoc:
        if framework is None:
            sys.exit("--refresh-godoc requires --framework")
        cache = refresh_godoc(framework)
        godoc_path.write_text(
            json.dumps(cache, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        print(
            f"wrote {godoc_path.relative_to(REPO)} "
            f"({len(cache['widgets'])} widgets, {len(cache['packages'])} packages)"
        )
    else:
        if not godoc_path.exists():
            sys.exit("data/godoc.json missing; run with --refresh-godoc --framework <path>")
        cache = json.loads(godoc_path.read_text(encoding="utf-8"))

    godoc = cache["widgets"]
    pkgs = cache["packages"]

    slugs = [w["slug"] for w in manifest["widgets"]]
    if len(slugs) != manifest["widgetCount"]:
        sys.exit(f"manifest says {manifest['widgetCount']} widgets, lists {len(slugs)}")
    if len(set(slugs)) != len(slugs):
        sys.exit("duplicate slugs in manifest")
    missing = [s for s in slugs if s not in godoc]
    if missing:
        sys.exit(f"no godoc for: {', '.join(missing)}")
    missing_prose = [s for s in slugs if s not in prose_all]
    if missing_prose:
        sys.exit(f"no hand-written prose for: {', '.join(missing_prose)}")
    if "form" in prose_all:
        sys.exit("there is no Form widget; remove the entry")
    unknown = sorted(set(prose_all) - set(slugs) - {"_comment"})
    if unknown:
        sys.exit(f"prose for widgets not in the manifest: {', '.join(unknown)}")

    out_dir = REPO / "content/widgets"
    out_dir.mkdir(parents=True, exist_ok=True)

    for weight, w in enumerate(manifest["widgets"], start=1):
        enriched = dict(w, weight=weight)
        page = render_page(enriched, prose_all[w["slug"]], godoc, pkgs)
        (out_dir / f"{w['slug']}.md").write_text(page, encoding="utf-8")

    (out_dir / "_index.md").write_text(render_index(manifest, prose_all), encoding="utf-8")

    stale = sorted(set(p.stem for p in out_dir.glob("*.md")) - set(slugs) - {"_index"})
    if stale:
        sys.exit(f"pages in content/widgets/ with no manifest entry: {', '.join(stale)}")

    print(f"wrote {len(slugs)} widget pages + _index.md to {out_dir.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())